version: '3.4'
services:
  webapp:
    build:
        context: .
        dockerfile: DockerSample/Dockerfile
    image: dotnet/sample
    ports: 
      - '8098:80'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    #   - ASPNETCORE_Kestrel__Certificates__Default__Password=password
    #   - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx